version: "3.9"

services:
  db:
    image: postgres:14.1-alpine
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  web:
    build: .
    command: sh -c "sleep 5 && python manage.py migrate && python manage.py runserver 0.0.0.0:8000 --noreload"
    ports:
      - "8000:8000"
    environment:
      - DB_NAME=postgres
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_URL=db
      - DB_PORT=5432
      - EXPIRES_AFTER_SEC=30
    depends_on:
      - db