apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.dbName }}
  labels:
    app: {{ .Values.dbName }}
spec:
  type: NodePort
  ports:
   - port: {{ .Values.service.port }}
  selector:
   app: {{ .Values.dbName }}