# statefulset.yml
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres-database
spec:
  selector:
    matchLabels:
      app: postgres-database
  serviceName: postgres-database
  replicas: 3
  template:
    metadata:
      labels:
        app: postgres-database
    spec:
      containers:
        - name: postgres-database
          image: postgres:10.1
          volumeMounts:
            - name: postgres-disk
              mountPath: /var/lib/postgresql/data

          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: cc-app-secret
                  key: db-user

            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: cc-app-secret
                  key: db-password
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata

          envFrom:
            - configMapRef:
                name: cc-app-configmap

  volumeClaimTemplates:
    - metadata:
        name: postgres-disk
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 10Gi